### ISSUE TITLE
Load model request failing with docker-compose

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-stack-analysis#12]
The request `/api/v1/schemas/kronos_load` failes to load sometimes. Works after running docker-compose again, but takes more than 5 mins to load successfully.

**Comment by tuhinsharma** [comment]
This functionality was temporary and removed now #15 . The time was high as the model size was more >300mb. Based on the #15 the model will be loaded when the pod comes up. Fixing issue #14 will resolve the loading time as well.

**Comment by tuhinsharma** [comment]
closing the issue. Feel free to re open if you face further problem.

**Comment by sara-02** [comment]
LGTM with #15 providing the fix.
