### ISSUE TITLE
Maven Socring takes 6.02 mins to return results( via docker-compose)

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-stack-analysis#14]
When the `http://0.0.0.0:6006/api/v1/schemas/kronos_scoring` request is fired with the following:
```
[
        {
            "ecosystem": "maven",
            "comp_package_count_threshold": 2,
            "alt_package_count_threshold": 4,
            "outlier_probability_threshold": 0.8,
            "unknown_packages_ratio_threshold": 0.3,
            "package_list": [
            	"org.mongodb:mongodb-driver-async",
                "io.vertx:vertx-core",
                "io.vertx:vertx-web"
			]
        }
    ]
```
Then a **successful response** is returned in **6.02 minutes.**
**Support threshold for training: 27**

**Comment by tuhinsharma** [comment]
@sara-02 some of the packages are having a large number of topics (>10). For example, com.linecorp.armeria:armeria is having 18 topics. 2^18 entries in the CPT of the PGM is huge. Need to clean the topics. <4 topics for each topics will do fine in terms of response time.

**Comment by sara-02** [comment]
@tuhinsharma Thanks. 
Reducing the topic list to under 4 reduced the model size. Now with **Support threshold for training: 30**, the scoring time has reduced to **6.7 seconds**
