### ISSUE TITLE
Empty Response when user input has duplicate packages

### ISSUE THREAD

**Issue by abs51295** [fabric8-analytics/fabric8-analytics-stack-analysis#160]
When a request is sent to PGM with duplicate packages, the response received is empty. For example:

Request: 
```json
[
    {
        "ecosystem": "maven",
        "comp_package_count_threshold": 5,
        "alt_package_count_threshold": 2,
        "outlier_probability_threshold": 0.88,
        "unknown_packages_ratio_threshold": 0.3,
        "package_list": [
          "io.vertx:vertx-core",
          "io.vertx:vertx-core",
          "io.vertx:vertx-web"
       ]
    }
]		
```

Response:
```json
[
    {
        "alternate_packages": {},
        "companion_packages": [],
        "ecosystem": "maven",
        "missing_packages": [],
        "outlier_package_list": [],
        "package_to_topic_dict": {},
        "user_persona": "1"
    }
]
```

**Comment by sara-02** [comment]
As pointed out by @abs51295 it is this [function](https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/blob/master/analytics_platform/kronos/src/kronos_online_scoring.py#L175) which is causing no recommendations to be returned, as adding duplicates fails this [line ](https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/blob/master/analytics_platform/kronos/src/kronos_online_scoring.py#L185).
