### ISSUE TITLE
Split into multiple repositories

### ISSUE THREAD

**Issue by msrb** [fabric8-analytics/fabric8-analytics-stack-analysis#4]
It seems like there are 3 services in this repository. There is nothing wrong with it, but it means that PR/commit affecting just one of the services will still trigger build, test and deployment of all 3 of them.

 Having each service in a separate repository would enable us to do more fine-grained CI/CD.

**Comment by sara-02** [comment]
@msrb Going forward we might add more components under the `analytics_platform` folder, one of them is a WIP PR #2 . So are you saying that each of those components should have its own repo?

**Comment by msrb** [comment]
Hey Sarah,

> So are you saying that each of those components should have its own repo?

It depends... if you don't share code between the components and if you expect to have a separate Docker image for each of them, then I'd say it would be better to have them in separate repositories. But if things are more complicated, then it's up to discussion :)

**Comment by vpavlin** [comment]
I second Michal's suggestion - if there are 3 images - i.e. 3 microservices - it would be best to split into 3 repos. If there is any shared code, that should be also split out into a library.

**Comment by TuhinSharma** [comment]
Yes. I completely agree with you guys. While we started this project we believed that keeping 3 microservices would be useful from PGM perspective. But later on we realised, there are only 2 potential microservices as KRONOS and JANUS [WIP]. GNOSIS, SOFTNET and KRONOS are tightly coupled as for the training part they need to be invoked sequentially on AWS EMR (It will be quite troublesome to keep track of the ending time for each training job for respective components) while there is only one user facing service which is KRONOS. I am working on making only one service KRONOS out of these 3 services. Please share your thoughts.

**Comment by miteshvp** [comment]
+1 to Michal and Vasek here. Tuhin make sure if there is a shared codebase that can be used across multiple different services, should be moved under a separate repo as library. Rest I agree with one service for KRONOS currently so one repo is enough.

**Comment by TuhinSharma** [comment]
Created #7 .It requires some more iterations though. We can keep this issue open and revisit this later. Please share your views.

**Comment by msrb** [comment]
Thanks @tuhinsharma :) please feel free to close this issue :wink:
