### ISSUE TITLE
Unified test folder

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-stack-analysis#49]
Currently the unit  test for each component are in its respective folder, need to restructure the folders and have all tests under one test folder.

**Comment by sara-02** [comment]
Fixed in #65

**Comment by fridex** [comment]
BTW if you add "Fixes: #49" to commit message, GitHub will automatically close this issue once the PR will gets merged. Can simplify things and tracking issues.

**Comment by sara-02** [comment]
Thanks, will keep that in mind. 👍

**Comment by sara-02** [comment]
Fixed.
